databases:
  - name: busbuddy-db
    plan: free

services:
  - type: web
    name: busbuddy
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: cd busbuddy && gunicorn busbuddy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: busbuddy-db
          property: connectionString
