# Generated by Django 5.2.6 on 2025-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_ac',
            field=models.BooleanField(default=False, verbose_name='Is this an AC bus?'),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_sleeper',
            field=models.BooleanField(default=False, verbose_name='Is this a Sleeper bus?'),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_women_safe',
            field=models.BooleanField(default=False, help_text='Check if this bus has features like reserved seats for women or security staff.', verbose_name='Women Safety Certified?'),
        ),
    ]
