# Generated by Django 5.2.6 on 2025-11-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bus_is_ac_bus_is_sleeper_bus_is_women_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='is_women_safe',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='Default bus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='is_women_safename',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fleet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_sleeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
