# Generated by Django 5.2.6 on 2025-11-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bus_created_at_remove_bus_is_women_safe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='is_women_safename',
            new_name='is_women_safe',
        ),
    ]
