# Generated by Django 5.2.6 on 2025-11-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_is_women_safename_bus_is_women_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_women_safe',
        ),
    ]
