# Generated by Django 5.2.6 on 2025-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_ac',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='is_women_safe',
        ),
        migrations.AddField(
            model_name='bus',
            name='ac_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non AC')], default='Non-AC', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('Seater', 'Seater'), ('Sleeper', 'Sleeper'), ('Both', 'Both')], default='Seater', max_length=20),
        ),
    ]
