# Generated by Django 5.2.6 on 2025-11-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_bus_is_ac_remove_bus_is_women_safe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_list', to='main.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
