# Generated by Django 5.2.6 on 2025-11-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='origin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='stops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='ac_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('Seater', 'Seater'), ('Sleeper', 'Sleeper'), ('Both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fleet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.CharField(max_length=50),
        ),
    ]
