# Generated by Django 5.2.6 on 2025-12-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_bus_conductor_remove_schedule_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='main.conductor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.route'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.bus'),
        ),
    ]
