# Generated by Django 5.2.6 on 2025-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bus_conductor_schedule_route_alter_schedule_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
